replicaCount: 1
image:
  repository: furryman/fuhriman-website
  tag: ga-2026.05.21-0658
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: fuhriman.org
      paths:
        - path: /
          pathType: Prefix
    - host: www.fuhriman.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fuhriman-tls
      hosts:
        - fuhriman.org
        - www.fuhriman.org
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
